// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Webboard.Infrastructure.Configuration;

#nullable disable

namespace Webboard.Infrastructure.Configuration.Migrations
{
    [DbContext(typeof(WebboardDbContext))]
    [Migration("20260929103918_AddMonitoringHistory")]
    partial class AddMonitoringHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Webboard.Infrastructure.Configuration.Entities.AuditLogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("ActorId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("integer");

                    b.Property<string>("Failure")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("HostId")
                        .HasColumnType("integer");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<string>("Operation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Outcome")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Output")
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)");

                    b.Property<string>("TargetSnapshot")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DateCreated");

                    b.HasIndex("OperationId")
                        .IsUnique();

                    b.HasIndex("DateCreated", "Id");

                    b.HasIndex("Action", "DateCreated", "Id");

                    b.HasIndex("ActorId", "DateCreated", "Id");

                    b.HasIndex("HostId", "DateCreated", "Id");

                    b.HasIndex("ModuleId", "DateCreated", "Id");

                    b.HasIndex("UserId", "DateCreated", "Id");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("Webboard.Infrastructure.Configuration.Entities.HostEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentBaseUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeletionFlag")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Hosts", (string)null);
                });

            modelBuilder.Entity("Webboard.Infrastructure.Configuration.Entities.LatestMonitoringEntity", b =>
                {
                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ConfigurationRevision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("FreshUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long?>("PingMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ModuleId");

                    b.ToTable("LatestMonitoring", (string)null);
                });

            modelBuilder.Entity("Webboard.Infrastructure.Configuration.Entities.ModuleCommandEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommandId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("HostId")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HostId");

                    b.HasIndex("ModuleId", "HostId", "CommandId")
                        .IsUnique();

                    b.ToTable("ModuleCommands", (string)null);
                });

            modelBuilder.Entity("Webboard.Infrastructure.Configuration.Entities.ModuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContainerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeletionFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HealthCheckUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int?>("HostId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ManagementUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("MinecraftServerAddress")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<int?>("MinecraftServerPort")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("SteamQueryPlayers")
                        .HasColumnType("boolean");

                    b.Property<int?>("SteamQueryPort")
                        .HasColumnType("integer");

                    b.Property<string>("SteamServerAddress")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HostId");

                    b.HasIndex("TypeId");

                    b.ToTable("Modules", null, t =>
                        {
                            t.HasCheckConstraint("CK_Modules_SteamPort", "\"SteamQueryPort\" IS NULL OR \"SteamQueryPort\" BETWEEN 1 AND 65535");
                        });
                });

            modelBuilder.Entity("Webboard.Infrastructure.Configuration.Entities.ModuleTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("ModuleTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Description = "Steam A2S game server",
                            Name = "Steam"
                        },
                        new
                        {
                            Id = 1,
                            Description = "Http Module",
                            Name = "Http"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Docker container",
                            Name = "Docker"
                        },
                        new
                        {
                            Id = 3,
                            Description = "systemd service",
                            Name = "Systemd"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Minecraft Java Edition server",
                            Name = "Minecraft"
                        });
                });

            modelBuilder.Entity("Webboard.Infrastructure.Configuration.Entities.MonitoringResultEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ConfigurationRevision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FreshUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<long?>("PingMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("ModuleId", "Timestamp", "Id");

                    b.ToTable("MonitoringResults", (string)null);
                });

            modelBuilder.Entity("Webboard.Infrastructure.Configuration.Entities.UserCrudAccessEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanCreate")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDisable")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanEnable")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanExecuteCommand")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanRestart")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanStart")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanStop")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanUpdate")
                        .HasColumnType("boolean");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Resource")
                        .IsUnique();

                    b.ToTable("UserCrudAccess", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserCrudAccess_Operations", "\"Resource\" = 'Modules' OR (NOT \"CanStart\" AND NOT \"CanStop\" AND NOT \"CanRestart\" AND NOT \"CanEnable\" AND NOT \"CanDisable\" AND NOT \"CanExecuteCommand\")");

                            t.HasCheckConstraint("CK_UserCrudAccess_ReadOnlyResources", "\"Resource\" NOT IN ('ModuleTypes', 'AuditLogs', 'MonitoringHistory') OR (NOT \"CanCreate\" AND NOT \"CanUpdate\" AND NOT \"CanDelete\")");

                            t.HasCheckConstraint("CK_UserCrudAccess_Resource", "\"Resource\" IN ('Users', 'Hosts', 'Modules', 'ModuleTypes', 'AuditLogs', 'MonitoringHistory')");
                        });
                });

            modelBuilder.Entity("Webboard.Infrastructure.Configuration.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeletionFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Webboard.Infrastructure.Configuration.Entities.AuditLogEntity", b =>
                {
                    b.HasOne("Webboard.Infrastructure.Configuration.Entities.UserEntity", "Actor")
                        .WithMany("AuditLogsAsActor")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Webboard.Infrastructure.Configuration.Entities.HostEntity", "Host")
                        .WithMany("AuditLogs")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Webboard.Infrastructure.Configuration.Entities.ModuleEntity", "Module")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Webboard.Infrastructure.Configuration.Entities.UserEntity", "User")
                        .WithMany("AuditLogsAsTarget")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Actor");

                    b.Navigation("Host");

                    b.Navigation("Module");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Webboard.Infrastructure.Configuration.Entities.LatestMonitoringEntity", b =>
                {
                    b.HasOne("Webboard.Infrastructure.Configuration.Entities.ModuleEntity", null)
                        .WithOne()
                        .HasForeignKey("Webboard.Infrastructure.Configuration.Entities.LatestMonitoringEntity", "ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Webboard.Infrastructure.Configuration.Entities.ModuleCommandEntity", b =>
                {
                    b.HasOne("Webboard.Infrastructure.Configuration.Entities.HostEntity", "Host")
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Webboard.Infrastructure.Configuration.Entities.ModuleEntity", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Host");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Webboard.Infrastructure.Configuration.Entities.ModuleEntity", b =>
                {
                    b.HasOne("Webboard.Infrastructure.Configuration.Entities.HostEntity", "Host")
                        .WithMany("Modules")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Webboard.Infrastructure.Configuration.Entities.ModuleTypeEntity", "Type")
                        .WithMany("Modules")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Host");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Webboard.Infrastructure.Configuration.Entities.MonitoringResultEntity", b =>
                {
                    b.HasOne("Webboard.Infrastructure.Configuration.Entities.ModuleEntity", null)
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Webboard.Infrastructure.Configuration.Entities.UserCrudAccessEntity", b =>
                {
                    b.HasOne("Webboard.Infrastructure.Configuration.Entities.UserEntity", "User")
                        .WithMany("CrudAccess")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Webboard.Infrastructure.Configuration.Entities.HostEntity", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("Webboard.Infrastructure.Configuration.Entities.ModuleEntity", b =>
                {
                    b.Navigation("AuditLogs");
                });

            modelBuilder.Entity("Webboard.Infrastructure.Configuration.Entities.ModuleTypeEntity", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("Webboard.Infrastructure.Configuration.Entities.UserEntity", b =>
                {
                    b.Navigation("AuditLogsAsActor");

                    b.Navigation("AuditLogsAsTarget");

                    b.Navigation("CrudAccess");
                });
#pragma warning restore 612, 618
        }
    }
}
