// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Webboard.Infrastructure.Configuration;

#nullable disable

namespace Webboard.Infrastructure.Configuration.Migrations
{
    [DbContext(typeof(WebboardDbContext))]
    [Migration("20260820144601_FixModuleTypeForeignKey")]
    partial class FixModuleTypeForeignKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Webboard.Infrastructure.Configuration.Entities.AuditLogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("integer");

                    b.Property<string>("AuditComment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DateCreated");

                    b.HasIndex("ModuleId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("Webboard.Infrastructure.Configuration.Entities.ManagedHostEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentBaseUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ManagedHosts", (string)null);
                });

            modelBuilder.Entity("Webboard.Infrastructure.Configuration.Entities.ModuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("HealthCheckUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("ManagedHostId")
                        .HasColumnType("integer");

                    b.Property<string>("ManagementUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("ModuleTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("ShowOnOverview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TargetIdentifier")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ModuleTypeId");

                    b.HasIndex("ManagedHostId", "SortOrder");

                    b.ToTable("Modules", (string)null);
                });

            modelBuilder.Entity("Webboard.Infrastructure.Configuration.Entities.ModuleTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("ModuleTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Http Module",
                            Type = "Http"
                        });
                });

            modelBuilder.Entity("Webboard.Infrastructure.Configuration.Entities.AuditLogEntity", b =>
                {
                    b.HasOne("Webboard.Infrastructure.Configuration.Entities.ModuleEntity", "Module")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Webboard.Infrastructure.Configuration.Entities.ModuleEntity", b =>
                {
                    b.HasOne("Webboard.Infrastructure.Configuration.Entities.ManagedHostEntity", "ManagedHost")
                        .WithMany("Modules")
                        .HasForeignKey("ManagedHostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Webboard.Infrastructure.Configuration.Entities.ModuleTypeEntity", "Type")
                        .WithMany()
                        .HasForeignKey("ModuleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ManagedHost");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Webboard.Infrastructure.Configuration.Entities.ManagedHostEntity", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("Webboard.Infrastructure.Configuration.Entities.ModuleEntity", b =>
                {
                    b.Navigation("AuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
